### ISSUE TITLE
Not much to do with the this repository 😁

### ISSUE THREAD

**Issue by tynguyen2k1** [anhsirk0/fetch-master-6000#27]
I wonder how you can show "≻⊲⋗". I cannot reproduce that.
I'm using Fira Code Retina font
![image](https://user-images.githubusercontent.com/64082226/141523820-9a4e6b97-3bba-41f7-bb78-28ad44392408.png)

**Comment by anhsirk0** [comment]
I am using Starship prompt.

Add this to your starship.toml file
`
[character]
success_symbol = "[≻⊲⋗](bold blue)"
`

select a nice font for  Bold Variant (otherise it wont look right)
I am using Fira Code Retina too , but for bold i am using Hack

In alacritty config file add this:
`
font:
   normal:
       family: Fira Code Retina
   bold:
       family: Hack
`

The key is to use proper font for bold , here are few that works:
Hack , DejaVu Sans Mono

**Comment by anhsirk0** [comment]
![screenshot111321122248](https://user-images.githubusercontent.com/59538102/141609250-75b54732-da75-46c4-a0eb-626668d12444.png)

![screenshot111321122236](https://user-images.githubusercontent.com/59538102/141609251-c8879784-d345-45ba-bac9-ed944f86992e.png)

**Comment by tynguyen2k1** [comment]
Thank you but it still doesn't work for me. It's strange. Maybe I should give up :(

**Comment by anhsirk0** [comment]
Tell me about your config, which shell, terminal, font , prompt etc etc

**Comment by tynguyen2k1** [comment]
Here are all my configs:

```
OS: Arch Linux
Shell: zsh 5.8
DE: Plasma 5.23.3
Terminal: alacritty
```

`~/.config/starship.toml`
```toml

# time out command
command_timeout = 1000

# Inserts a blank line between shell prompts
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[≻⊲⋗](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
# error_symbol = "[✗](bold red) "
error_symbol = "[-_-](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

#[custom.docker]
#files = ["docker-compose.yml"]
#format = "via [🐋 $context](blue bold)"
```
`~/.config/alacritty/alacritty.yml`
```yml
schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'
# "storm" uses a lighter BG color
colors: *tokyo-night-storm

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    # family: Source Code Pro
    # family: Hack
    # family: DejaVu Sans Mono
    # family: JetBrains Mono
    # family: TerminessTTF Nerd Font
    # family: NotoSansMono Nerd Font
    #family: MesloLGL Nerd Font
    family: Fira Code Retina

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Source Code Pro
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    family: Hack
    # family: Fira Code SemiBold
    #family: DejaVu Sans Mono
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofur Nerd Font
    # family: TerminessTTF Nerd Font
    # family: NotoSansMono Nerd Font


    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Source Code Pro Mono
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    family: Hack
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofuritalic Nerd Font Mono
    # family: TerminessTTF Nerd Font
    # family: NotoSansMono Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Source Code Pro Mono
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    # family: Hack
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofuritalic Nerd Font Mono
    # family: TerminessTTF Nerd Font
    family: Source Code Pro

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 1

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  #glyph_offset:
  #  x: 0
  #  y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  #use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

window:
  padding:
    x: 8
    y: 2

```
`~/.fonts.conf`
```conf
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <dir>~/.fonts</dir>
 <match target="font">
  <edit mode="assign" name="hinting">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="hintstyle">
   <const>hintslight</const>
  </edit>
 </match>
</fontconfig>
```
